baseURL = 'https://quay.cicy.de'
languageCode = 'en-gb'
paginate = 6
theme= "coHub"
title = 'QUAY Financials'

[Menu]
  # Main Menu
  [[menu.Main]]
  name = "QUAY"
  url= "/"
  weight = 1
  [[menu.Main]]
  name = "About"
  url= "/about/"
  weight = 3
  [[menu.Main]]
  name = "News"
  url= "#blog"
  weight = 4
  [[menu.Main]]
  name = "Open An Account"
  url= "#pricing"
  weight = 5
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 6
  [[menu.Main]]
  name = "Contact"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Conflicts of Interest"
  url = "/conflicts-of-interest/"
  weight = 3
  [[menu.sitemap]]
  name = "Execution Policy"
  url = "/execution-policy/"
  weight = 2
  [[menu.sitemap]]
  name = "Risk Warning"
  url = "/risk-warning/"
  weight = 1
  [[menu.sitemap]]
  name = "Data Protection"
  url = "/dataprotection/"
  weight = 4

[params]
  aboutPageURL = "blog"
  servicesPageURL = "services"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://quay-financials.com/imprint\" target=\"_blank\">QUAY </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-"
  logo = "images/logo-quay-lightblue-smooth.png"
  footerlogo = "images/logo-quay.png"
  footerDescription = "Quay Financials is authorised and regulated as an Investment Dealer by the Gibraltar Financial Services Commission. Its licence also requires compliance with the Markets in Financial Instruments Directive and Regulations (MiFID/MiFIR) at least until the expected departure of the United Kingdom and Gibraltar from the European Union."

  [params.address]
  address = "Quay Financials Limited,"
  address2 = "Eurotowers Suite 3.2.13, Gibraltar – GX11 1AA"
  email = "sales@quayfinancials.com"
  openingDesc = "Give us a call or contact us by email."
  openingHours = "We endeavour to answer all enquiries within 24 hours on business days"
  phone = " +350 200 48733"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "36.1432837"
  longitude = "-5.3587071"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 3


[blackfriday]
extensions = [
  "hardLineBreak", # newlines result in line breaks
]

[markup.goldmark.renderer]
hardWraps = true